docs: ✏️ Adds summary to resources in readme
FieldControl/contaazul pull request #2
Opened 2020-01-27 16:20 UTC by marciofmjr

2020-01-28 00:28 UTC, lfreneda requested changes
Se o sumário for conter apenas os recursos, deve ficar na seção de "Usage". 

Se for pra ficar no topo, deve conter todas as seções: Installation, Playground, Usage, Pull Request and License.

Faz sentido?

2020-01-28 13:46 UTC, marciofmjr commented
> Se o sumário for conter apenas os recursos, deve ficar na seção de "Usage".
> 
> Se for pra ficar no topo, deve conter todas as seções: Installation, Playground, Usage, Pull Request and License.
> 
> Faz sentido?

eu pensei em colocar todas as seçõe, mas como elas estão muito pequenas, da pra ver as seções na mesma página sem rolar, por isso, achei que não seria necessário no momento.. o que você acha ?

2020-02-05 00:39 UTC, lfreneda commented
Vamos ver como fica e qualquer coisa depois a gente altera :)

2020-02-05 00:40 UTC, lfreneda approved these changes
:ok_hand:

2020-02-05 00:40 UTC, merged